global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'loan-service'
    scrape_interval: 5s
    static_configs:
      - targets: ['loan-service:3000']
    metrics_path: /metrics

  - job_name: 'device-service'
    scrape_interval: 5s
    static_configs:
      - targets: ['device-service:3000']
    metrics_path: /metrics
